### ISSUE TITLE
bug(handleNewContest): Already started events are not removed from upcomingEvents

### ISSUE THREAD

**Issue by zolbooo** [Akiko643/discord-contest-bot#1]
**Describe the bug**
`prepareNotifications` function in `@/notifications/contest` doesn't add timeout for contest start.

**To Reproduce**
1. Start bot, it'll pick up some contest
2. Wait contest to start

**Expected behavior**
Contest would be removed after start (`contest.startTime`)

**Comment by khanka0511** [comment]
I'd like to tackle this issue
